### ISSUE TITLE
use aprilmav for outdoor application 

### ISSUE THREAD

**Issue by mohammada315** [stephendade/aprilmav#1]
dear @stephendade 
is that possible to use aprilmav for outdoor application ?
and i want to use it on my drone(quad) 

do you have similar experience , does it have limitation in distance 
i can used big tag for example

**Comment by stephendade** [comment]
It should be possible to use outdoors, but I've not tried it myself.

The maximum distance from the tag is related to it's size and the camera resolution. So if you need more than 2m range, you'll need bigger (larger than A4) tags or a higher resolution (>1MP) camera.

**Comment by mohammada315** [comment]
Thank you very much for the explanation

**Comment by mohammada315** [comment]
Do you think this camera has a good performance?
[Arducam 12MP MINI IMX477 Synchronized Stereo Camera Bundle Kit for Raspberry Pi
](https://www.aliexpress.com/item/3256803271798665.html?spm=a2g0o.productlist.0.0.1214165c9DWnUD&algo_pvid=a2c0d717-02c1-4ea8-aa71-f5cb1f304f7f&aem_p4p_detail=202208052141232528520349020120038120037&algo_exp_id=a2c0d717-02c1-4ea8-aa71-f5cb1f304f7f-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025877969004%22%7D&pdp_npi=2%40dis%21USD%21470.44%21470.44%21%21%21%21%21%400b0a187916597608831076651e2c1f%2112000025877969004%21sea&curPageLogUid=L4FXl6TaYsnD)


or

[Arducam 2MP Global Shutter OG02B10 Color Camer
](https://www.aliexpress.com/item/3256804287395748.html?spm=a2g0o.productlist.0.0.1214165c9DWnUD&algo_pvid=a2c0d717-02c1-4ea8-aa71-f5cb1f304f7f&algo_exp_id=a2c0d717-02c1-4ea8-aa71-f5cb1f304f7f-4&pdp_ext_f=%7B%22sku_id%22%3A%2212000029288933172%22%7D&pdp_npi=2%40dis%21USD%21192.08%21192.08%21%21%21%21%21%400b0a187916597608831076651e2c1f%2112000029288933172%21sea&curPageLogUid=uVihHxIgW7gQ)

**Comment by stephendade** [comment]
AprilMAV would struggle to process the frames from a 12MP camera in realtime.

I would suggest going with the 2MP camera for that reason.
